'use stric'

// Object of data SQL for auth of admin users and sellers users:
module.exports = {

	//Administrators:
	DataAdmin: 'SELECT a.idadministrator AS "iduser", a.email AS "email", a.state AS "state", a.cellphone AS "cellphone", s.address AS "address", s.name AS "storeName", s.idshop AS "id", b.name AS "bank", b.state AS "stateBank", ba.num AS "accountNumber", ba.state AS "stateAccount", h.name AS "accountHolder", h.document AS "documentHolder", h.state AS "stateHolder", c.alias AS "coin", c.state AS "stateCoin", t2.sales AS "numberSales", t1.money AS "money", cy.name AS "city", cy.state AS "stateCity", st.name AS "department", st.state AS "stateDepartament", cn.name AS "country", cn.state AS "stateCountry" FROM banks_accounts AS ba LEFT JOIN holders AS h ON ba.idholder = h.idholder INNER JOIN coins AS c ON ba.idcoin = c.idcoin INNER JOIN banks AS b ON ba.idbank = b.idbank RIGHT JOIN shops AS s ON ba.idbankaccount = s.idbankaccount LEFT JOIN administrators AS a ON a.idadministrator = s.idadministrator LEFT JOIN (	SELECT pp1.idshop AS shop, sum(pp1.amount) AS "money" FROM payments_pendings AS pp1 WHERE state = true GROUP BY shop) AS t1 ON t1.shop = s.idShop LEFT JOIN (	SELECT pp2.idshop AS shop, count(*) AS "sales" FROM payments_pendings AS pp2 GROUP BY shop) AS t2 ON t2.shop = s.idShop LEFT JOIN cities AS cy ON s.idcity = cy.idcity LEFT JOIN states AS st ON st.idstate = cy.idstate LEFT JOIN countries AS cn ON cn.idcountry = st.idcountry WHERE s.idshop = $idshop OR a.idadministrator = $idadmin AND s.state != false AND a.state != $state',

	// Sellers:
	DataSeller:'SELECT se.idseller AS "iduser", se.state AS "state", a.email AS "email", a.cellphone AS "cellphone", s.address AS "address", s.name AS "storeName", s.idshop AS "id", b.name AS "bank", b.state AS "stateBank", ba.num AS "accountNumber", ba.state AS "stateAccount", h.name AS "accountHolder", h.document AS "documentHolder", h.state AS "stateHolder", c.alias AS "coin", c.state AS "stateCoin", t2.sales as "numberSales", t1.money as "money", cy.name AS "city", cy.state AS "stateCity", st.name AS "department", st.state AS "stateDepartament", cn.name AS "country", cn.state AS "stateCountry" FROM banks_accounts AS ba LEFT JOIN holders AS h ON ba.idholder = h.idholder INNER JOIN coins AS c ON ba.idcoin = c.idcoin INNER JOIN banks AS b ON ba.idbank = b.idbank RIGHT JOIN shops AS s ON ba.idbankaccount = s.idbankaccount LEFT JOIN sellers AS se ON se.idshop = s.idshop LEFT JOIN administrators AS a ON a.idadministrator = s.idadministrator LEFT JOIN (	SELECT pp1.idshop AS shop, sum(pp1.amount) AS "money" FROM payments_pendings AS pp1 WHERE state = true GROUP BY shop) AS t1 ON t1.shop = s.idShop LEFT JOIN (	SELECT pp2.idshop AS shop, count(*) AS "sales" FROM payments_pendings AS pp2 GROUP BY shop) AS t2 ON t2.shop = s.idShop LEFT JOIN cities AS cy ON s.idcity = cy.idcity LEFT JOIN states AS st ON st.idstate = cy.idstate LEFT JOIN countries AS cn ON cn.idcountry = st.idcountry WHERE se.idseller = $idseller AND a.state != $state AND se.state != $state AND s.state != false'

}
